Remove tuner dependency
Fixes up an issue introduced with the commit below
https://github.com/Mazda--/frameworks_base/commit/86f4374e7a57685787eee517ccd2ad3cc06a2291

ERROR: /home/jayantdeshmukh181115/screwd/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/QSFooterImpl.java:349.30: The method isTunerEnabled(Context) is undefined for the type TunerService
ERROR: /home/jayantdeshmukh181115/screwd/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/QSFooterImpl.java:408.38: The method isTunerEnabled(Context) is undefined for the type TunerService
ERROR: /home/jayantdeshmukh181115/screwd/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/QSFooterImpl.java:409.38: The method showResetRequest(Context, () -> {}) is undefined for the type TunerService
ERROR: /home/jayantdeshmukh181115/screwd/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/QSFooterImpl.java:416.38: The method setTunerEnabled(Context, boolean) is undefined for the type TunerService